development: &default
  adapter: postgresql
  database: ads_development
  encoding: utf8
  host: localhost
  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *default
  adapter:  postgresql
  database: ads_development

test:
  <<: *default
  database: ads_test

production:
  <<: *default
  database: ads_production

docker:
  adapter: postgresql
  database: postgres
  encoding: utf8
  username: postgres
  password:
  host: db
  pool: 5
